package gitops

import (
	"strings"
	"testing"

	"github.com/davidacain/platform-lab/tools/k8s-resource-inspector/pkg/plan"
)

func TestGenerateValuesFile_single(t *testing.T) {
	containers := []plan.ContainerPlan{
		{Name: "app", CPURequest: "10m", CPULimit: "10m", MemRequest: "16Mi", MemLimit: "16Mi"},
	}
	got, err := generateValuesFile(containers)
	if err != nil {
		t.Fatalf("generateValuesFile() error: %v", err)
	}
	s := string(got)

	if !strings.HasPrefix(s, "# Generated by kri") {
		t.Error("missing generated-by header")
	}
	if !strings.Contains(s, "resources:") {
		t.Error("missing top-level resources: key")
	}
	if strings.Contains(s, "containers:") {
		t.Error("single-container output should not contain containers: key")
	}
	if !strings.Contains(s, "cpu: 10m") {
		t.Error("missing cpu: 10m")
	}
	if !strings.Contains(s, "memory: 16Mi") {
		t.Error("missing memory: 16Mi")
	}
}

func TestGenerateValuesFile_multi(t *testing.T) {
	containers := []plan.ContainerPlan{
		{Name: "server", CPURequest: "10m", CPULimit: "10m", MemRequest: "16Mi", MemLimit: "16Mi"},
		{Name: "sidecar", CPURequest: "5m", CPULimit: "5m", MemRequest: "8Mi", MemLimit: "8Mi"},
	}
	got, err := generateValuesFile(containers)
	if err != nil {
		t.Fatalf("generateValuesFile() error: %v", err)
	}
	s := string(got)

	if !strings.Contains(s, "containers:") {
		t.Error("multi-container output missing containers: key")
	}
	if !strings.Contains(s, "name: server") {
		t.Error("missing name: server")
	}
	if !strings.Contains(s, "name: sidecar") {
		t.Error("missing name: sidecar")
	}
	if !strings.Contains(s, "cpu: 10m") {
		t.Error("missing cpu: 10m for server")
	}
	if !strings.Contains(s, "cpu: 5m") {
		t.Error("missing cpu: 5m for sidecar")
	}
	// Should not use top-level resources: key
	if strings.HasPrefix(strings.TrimSpace(strings.Split(s, "\n")[1]), "resources:") {
		t.Error("multi-container output should not start with top-level resources:")
	}
}

func TestGenerateValuesFile_singleHasRequestsAndLimits(t *testing.T) {
	containers := []plan.ContainerPlan{
		{Name: "app", CPURequest: "10m", CPULimit: "20m", MemRequest: "16Mi", MemLimit: "32Mi"},
	}
	got, err := generateValuesFile(containers)
	if err != nil {
		t.Fatalf("generateValuesFile() error: %v", err)
	}
	s := string(got)
	if !strings.Contains(s, "requests:") {
		t.Error("missing requests: block")
	}
	if !strings.Contains(s, "limits:") {
		t.Error("missing limits: block")
	}
}
