package gitops

import (
	"fmt"
	"os"
	"path"
	"path/filepath"
	"time"

	gogit "github.com/go-git/go-git/v5"
	"github.com/go-git/go-git/v5/plumbing"
	"github.com/go-git/go-git/v5/plumbing/object"
	"gopkg.in/yaml.v3"

	"github.com/davidacain/platform-lab/tools/k8s-resource-inspector/pkg/plan"
)

// PushValuesFile writes values-resources.yaml on a new branch and force-pushes.
// The repo is cloned once via cache and reused across multiple apps in the same repo.
// Returns the branch name.
func PushValuesFile(cache *RepoCache, repoURL, appName, chartPath string, containers []plan.ContainerPlan, authorName, authorEmail string) (branchName string, err error) {
	e, err := cache.get(repoURL)
	if err != nil {
		return "", err
	}

	branchName = fmt.Sprintf("kri/%s-rightsizing", appName)
	branchRef := plumbing.NewBranchReferenceName(branchName)

	w, err := e.repo.Worktree()
	if err != nil {
		return "", fmt.Errorf("get worktree: %w", err)
	}

	if err := w.Checkout(&gogit.CheckoutOptions{
		Branch: branchRef,
		Create: true,
	}); err != nil {
		return "", fmt.Errorf("create branch %s: %w", branchName, err)
	}

	content, err := generateValuesFile(containers)
	if err != nil {
		return "", fmt.Errorf("generate values file: %w", err)
	}

	// valuesPath uses filepath.Join for OS filesystem write.
	valuesPath := filepath.Join(e.dir, chartPath, "values-resources.yaml")
	if err := os.WriteFile(valuesPath, content, 0644); err != nil {
		return "", fmt.Errorf("write values file: %w", err)
	}

	// repoRelPath uses path.Join (forward slashes) as required by go-git.
	repoRelPath := path.Join(chartPath, "values-resources.yaml")
	if _, err := w.Add(repoRelPath); err != nil {
		return "", fmt.Errorf("git add: %w", err)
	}

	if _, err := w.Commit(fmt.Sprintf("chore(kri): rightsizing for %s", appName), &gogit.CommitOptions{
		Author: &object.Signature{
			Name:  authorName,
			Email: authorEmail,
			When:  time.Now(),
		},
	}); err != nil {
		return "", fmt.Errorf("git commit: %w", err)
	}

	if err := e.repo.Push(&gogit.PushOptions{
		Auth:  e.auth,
		Force: true,
	}); err != nil {
		return "", fmt.Errorf("git push: %w", err)
	}

	return branchName, nil
}

// resource block types for structured YAML generation.
type resourcePair struct {
	CPU    string `yaml:"cpu"`
	Memory string `yaml:"memory"`
}

type resourceBlock struct {
	Requests resourcePair `yaml:"requests"`
	Limits   resourcePair `yaml:"limits"`
}

type singleContainerValues struct {
	Resources resourceBlock `yaml:"resources"`
}

type multiContainerEntry struct {
	Name      string        `yaml:"name"`
	Resources resourceBlock `yaml:"resources"`
}

type multiContainerValues struct {
	Containers []multiContainerEntry `yaml:"containers"`
}

// generateValuesFile returns the content of values-resources.yaml for the given containers.
// Single-container apps use the top-level resources: key.
// Multi-container apps use a containers: list.
func generateValuesFile(containers []plan.ContainerPlan) ([]byte, error) {
	header := []byte("# Generated by kri — do not edit manually\n")

	var data interface{}
	if len(containers) == 1 {
		c := containers[0]
		data = singleContainerValues{
			Resources: resourceBlock{
				Requests: resourcePair{CPU: c.CPURequest, Memory: c.MemRequest},
				Limits:   resourcePair{CPU: c.CPULimit, Memory: c.MemLimit},
			},
		}
	} else {
		entries := make([]multiContainerEntry, len(containers))
		for i, c := range containers {
			entries[i] = multiContainerEntry{
				Name: c.Name,
				Resources: resourceBlock{
					Requests: resourcePair{CPU: c.CPURequest, Memory: c.MemRequest},
					Limits:   resourcePair{CPU: c.CPULimit, Memory: c.MemLimit},
				},
			}
		}
		data = multiContainerValues{Containers: entries}
	}

	body, err := yaml.Marshal(data)
	if err != nil {
		return nil, fmt.Errorf("marshal values: %w", err)
	}
	return append(header, body...), nil
}
