package gitops

import (
	"fmt"
	"os"
	"path/filepath"
	"time"

	gogit "github.com/go-git/go-git/v5"
	"github.com/go-git/go-git/v5/plumbing"
	"github.com/go-git/go-git/v5/plumbing/object"
	githttp "github.com/go-git/go-git/v5/plumbing/transport/http"

	"github.com/davidacain/platform-lab/tools/k8s-resource-inspector/pkg/plan"
)

// PushValuesFile clones the repo, writes values-resources.yaml on a new branch,
// commits, and force-pushes. Returns the branch name.
func PushValuesFile(repoURL, token, appName, chartPath string, containers []plan.ContainerPlan, authorName, authorEmail string) (branchName string, err error) {
	tmpDir, err := os.MkdirTemp("", "kri-push-*")
	if err != nil {
		return "", fmt.Errorf("create temp dir: %w", err)
	}
	defer os.RemoveAll(tmpDir)

	auth := &githttp.BasicAuth{Username: "x-oauth-token", Password: token}

	repo, err := gogit.PlainClone(tmpDir, false, &gogit.CloneOptions{
		URL:   repoURL,
		Auth:  auth,
		Depth: 1,
	})
	if err != nil {
		return "", fmt.Errorf("clone %s: %w", repoURL, err)
	}

	branchName = fmt.Sprintf("kri/%s-rightsizing", appName)
	branchRef := plumbing.NewBranchReferenceName(branchName)

	w, err := repo.Worktree()
	if err != nil {
		return "", fmt.Errorf("get worktree: %w", err)
	}

	if err := w.Checkout(&gogit.CheckoutOptions{
		Branch: branchRef,
		Create: true,
	}); err != nil {
		return "", fmt.Errorf("create branch %s: %w", branchName, err)
	}

	content := generateValuesFile(containers)
	valuesPath := filepath.Join(tmpDir, chartPath, "values-resources.yaml")
	if err := os.WriteFile(valuesPath, []byte(content), 0644); err != nil {
		return "", fmt.Errorf("write values file: %w", err)
	}

	repoRelPath := filepath.Join(chartPath, "values-resources.yaml")
	if _, err := w.Add(repoRelPath); err != nil {
		return "", fmt.Errorf("git add: %w", err)
	}

	if _, err := w.Commit(fmt.Sprintf("chore(kri): rightsizing for %s", appName), &gogit.CommitOptions{
		Author: &object.Signature{
			Name:  authorName,
			Email: authorEmail,
			When:  time.Now(),
		},
	}); err != nil {
		return "", fmt.Errorf("git commit: %w", err)
	}

	if err := repo.Push(&gogit.PushOptions{
		Auth:  auth,
		Force: true,
	}); err != nil {
		return "", fmt.Errorf("git push: %w", err)
	}

	return branchName, nil
}

// generateValuesFile returns the content of values-resources.yaml for the given containers.
// Single-container apps use the top-level resources: key.
// Multi-container apps use a containers: list.
func generateValuesFile(containers []plan.ContainerPlan) string {
	header := "# Generated by kri — do not edit manually\n"

	if len(containers) == 1 {
		c := containers[0]
		return fmt.Sprintf(`%sresources:
  requests:
    cpu: %s
    memory: %s
  limits:
    cpu: %s
    memory: %s
`, header, c.CPURequest, c.MemRequest, c.CPULimit, c.MemLimit)
	}

	out := header + "containers:\n"
	for _, c := range containers {
		out += fmt.Sprintf(`  - name: %s
    resources:
      requests:
        cpu: %s
        memory: %s
      limits:
        cpu: %s
        memory: %s
`, c.Name, c.CPURequest, c.MemRequest, c.CPULimit, c.MemLimit)
	}
	return out
}
