package github

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"

	"github.com/davidacain/platform-lab/tools/k8s-resource-inspector/pkg/plan"
)

const apiBase = "https://api.github.com"

// EnsurePR creates a PR for the given branch, or returns the URL of an existing
// open PR if one already exists. created is true only when a new PR was opened.
func EnsurePR(token, repoURL, branch, appName string, containers []plan.ContainerPlan) (prURL string, created bool, err error) {
	owner, repo, err := parseRepoURL(repoURL)
	if err != nil {
		return "", false, err
	}

	existing, err := findOpenPR(token, owner, repo, branch)
	if err != nil {
		return "", false, err
	}
	if existing != "" {
		return existing, false, nil
	}

	url, err := createPR(token, owner, repo, branch, appName, containers)
	if err != nil {
		return "", false, err
	}
	return url, true, nil
}

func parseRepoURL(repoURL string) (owner, repo string, err error) {
	// Handle https://github.com/owner/repo and https://github.com/owner/repo.git
	repoURL = strings.TrimSuffix(repoURL, ".git")
	parts := strings.Split(strings.TrimPrefix(repoURL, "https://github.com/"), "/")
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		return "", "", fmt.Errorf("cannot parse GitHub repo from URL %q", repoURL)
	}
	return parts[0], parts[1], nil
}

func findOpenPR(token, owner, repo, branch string) (string, error) {
	url := fmt.Sprintf("%s/repos/%s/%s/pulls?head=%s:%s&state=open", apiBase, owner, repo, owner, branch)
	req, _ := http.NewRequest("GET", url, nil)
	req.Header.Set("Authorization", "Bearer "+token)
	req.Header.Set("Accept", "application/vnd.github+json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", fmt.Errorf("list PRs: %w", err)
	}
	defer resp.Body.Close()

	var prs []struct {
		HTMLURL string `json:"html_url"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&prs); err != nil {
		return "", fmt.Errorf("decode PR list: %w", err)
	}
	if len(prs) > 0 {
		return prs[0].HTMLURL, nil
	}
	return "", nil
}

func createPR(token, owner, repo, branch, appName string, containers []plan.ContainerPlan) (string, error) {
	title := fmt.Sprintf("chore(kri): rightsizing for %s", appName)
	body := buildPRBody(appName, containers)

	payload, _ := json.Marshal(map[string]string{
		"title": title,
		"body":  body,
		"head":  branch,
		"base":  "main",
	})

	url := fmt.Sprintf("%s/repos/%s/%s/pulls", apiBase, owner, repo)
	req, _ := http.NewRequest("POST", url, bytes.NewReader(payload))
	req.Header.Set("Authorization", "Bearer "+token)
	req.Header.Set("Accept", "application/vnd.github+json")
	req.Header.Set("Content-Type", "application/json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", fmt.Errorf("create PR: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusCreated {
		body, _ := io.ReadAll(resp.Body)
		return "", fmt.Errorf("create PR: HTTP %d: %s", resp.StatusCode, body)
	}

	var pr struct {
		HTMLURL string `json:"html_url"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&pr); err != nil {
		return "", fmt.Errorf("decode PR response: %w", err)
	}
	return pr.HTMLURL, nil
}

func buildPRBody(appName string, containers []plan.ContainerPlan) string {
	var sb strings.Builder
	sb.WriteString("## kri rightsizing recommendation\n\n")
	sb.WriteString("| Container | CPU request | CPU limit | MEM request | MEM limit |\n")
	sb.WriteString("|-----------|-------------|-----------|-------------|----------|\n")
	for _, c := range containers {
		fmt.Fprintf(&sb, "| %s | %s | %s | %s | %s |\n",
			c.Name, c.CPURequest, c.CPULimit, c.MemRequest, c.MemLimit)
	}
	sb.WriteString("\n_Generated by [kri](https://github.com/davidacain/platform-lab/tree/main/tools/k8s-resource-inspector)_\n")
	return sb.String()
}
