package github

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"

	"github.com/davidacain/platform-lab/tools/k8s-resource-inspector/pkg/plan"
)

// EnsurePR creates a PR for the given branch, or returns the URL of an existing
// open PR if one already exists. created is true only when a new PR was opened.
func EnsurePR(token, repoURL, branch string, p plan.AppPlan, baseBranch, apiURL string) (prURL string, created bool, err error) {
	owner, repo, err := parseRepoURL(repoURL)
	if err != nil {
		return "", false, err
	}

	existing, err := findOpenPR(token, apiURL, owner, repo, branch)
	if err != nil {
		return "", false, err
	}
	if existing != "" {
		return existing, false, nil
	}

	url, err := createPR(token, apiURL, owner, repo, branch, baseBranch, p)
	if err != nil {
		return "", false, err
	}
	return url, true, nil
}

func parseRepoURL(repoURL string) (owner, repo string, err error) {
	// Handle https://github.com/owner/repo and https://github.com/owner/repo.git
	repoURL = strings.TrimSuffix(repoURL, ".git")
	parts := strings.Split(strings.TrimPrefix(repoURL, "https://github.com/"), "/")
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		return "", "", fmt.Errorf("cannot parse GitHub repo from URL %q", repoURL)
	}
	return parts[0], parts[1], nil
}

func findOpenPR(token, apiURL, owner, repo, branch string) (string, error) {
	url := fmt.Sprintf("%s/repos/%s/%s/pulls?head=%s:%s&state=open", apiURL, owner, repo, owner, branch)
	req, _ := http.NewRequest("GET", url, nil)
	req.Header.Set("Authorization", "Bearer "+token)
	req.Header.Set("Accept", "application/vnd.github+json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", fmt.Errorf("list PRs: %w", err)
	}
	defer resp.Body.Close()

	var prs []struct {
		HTMLURL string `json:"html_url"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&prs); err != nil {
		return "", fmt.Errorf("decode PR list: %w", err)
	}
	if len(prs) > 0 {
		return prs[0].HTMLURL, nil
	}
	return "", nil
}

func createPR(token, apiURL, owner, repo, branch, baseBranch string, p plan.AppPlan) (string, error) {
	title := fmt.Sprintf("chore(kri): rightsizing for %s", p.App)
	body := buildPRBody(p)

	payload, _ := json.Marshal(map[string]string{
		"title": title,
		"body":  body,
		"head":  branch,
		"base":  baseBranch,
	})

	url := fmt.Sprintf("%s/repos/%s/%s/pulls", apiURL, owner, repo)
	req, _ := http.NewRequest("POST", url, bytes.NewReader(payload))
	req.Header.Set("Authorization", "Bearer "+token)
	req.Header.Set("Accept", "application/vnd.github+json")
	req.Header.Set("Content-Type", "application/json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", fmt.Errorf("create PR: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusCreated {
		body, _ := io.ReadAll(resp.Body)
		return "", fmt.Errorf("create PR: HTTP %d: %s", resp.StatusCode, body)
	}

	var pr struct {
		HTMLURL string `json:"html_url"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&pr); err != nil {
		return "", fmt.Errorf("decode PR response: %w", err)
	}
	return pr.HTMLURL, nil
}

func buildPRBody(p plan.AppPlan) string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "## kri rightsizing — %s\n", p.App)

	for _, c := range p.Containers {
		fmt.Fprintf(&sb, "\n#### %s\n", c.Name)
		fmt.Fprintf(&sb, "- **Behavior:** %s (confidence %s, %s window)\n", c.Behavior, c.Confidence, p.Window)
		fmt.Fprintf(&sb, "- **CPU:** p95 `%s` / p99 `%s` — `%s` -> `%s`\n",
			c.CPUP95, c.CPUP99, c.CurrentCPURequest, c.CPURequest)
		fmt.Fprintf(&sb, "- **MEM:** p95 `%s` / p99 `%s` (%s of limit) — `%s` -> `%s`\n",
			c.MemP95, c.MemP99, c.MemLimPct, c.CurrentMemRequest, c.MemRequest)
	}

	if p.HPAWarning != "" {
		fmt.Fprintf(&sb, "\n> **Warning:** %s\n", p.HPAWarning)
	}

	sb.WriteString("\n_Generated by kri_\n")
	return sb.String()
}

func buildHPAPRBody(p plan.AppPlan) string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "## kri HPA tuning — %s\n", p.App)

	if p.HPA != nil {
		h := p.HPA
		fmt.Fprintf(&sb, "\n**Reason:** %s\n", h.Reason)
		fmt.Fprintf(&sb, "**Metric driver:** %s\n", h.Driver)
		fmt.Fprintf(&sb, "**Recommended minReplicas:** %d\n", h.MinReplicas)
		if h.TargetCPUUtilizationPercentage != nil {
			fmt.Fprintf(&sb, "**Target CPU utilization:** %d%%\n", *h.TargetCPUUtilizationPercentage)
		}
		if h.TargetMemUtilizationPercentage != nil {
			fmt.Fprintf(&sb, "**Target memory utilization:** %d%%\n", *h.TargetMemUtilizationPercentage)
		}
		fmt.Fprintf(&sb, "\nObservation window: %s\n", p.Window)
	}

	sb.WriteString("\n_Generated by kri_\n")
	return sb.String()
}

// EnsureHPAPR creates an HPA tuning PR, or returns the URL of an existing open PR.
func EnsureHPAPR(token, repoURL, branch string, p plan.AppPlan, baseBranch, apiURL string) (prURL string, created bool, err error) {
	owner, repo, err := parseRepoURL(repoURL)
	if err != nil {
		return "", false, err
	}

	existing, err := findOpenPR(token, apiURL, owner, repo, branch)
	if err != nil {
		return "", false, err
	}
	if existing != "" {
		return existing, false, nil
	}

	title := fmt.Sprintf("chore(kri): hpa tuning for %s", p.App)
	body := buildHPAPRBody(p)

	payload, _ := json.Marshal(map[string]string{
		"title": title,
		"body":  body,
		"head":  branch,
		"base":  baseBranch,
	})

	url := fmt.Sprintf("%s/repos/%s/%s/pulls", apiURL, owner, repo)
	req, _ := http.NewRequest("POST", url, bytes.NewReader(payload))
	req.Header.Set("Authorization", "Bearer "+token)
	req.Header.Set("Accept", "application/vnd.github+json")
	req.Header.Set("Content-Type", "application/json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", false, fmt.Errorf("create HPA PR: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusCreated {
		body, _ := io.ReadAll(resp.Body)
		return "", false, fmt.Errorf("create HPA PR: HTTP %d: %s", resp.StatusCode, body)
	}

	var pr struct {
		HTMLURL string `json:"html_url"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&pr); err != nil {
		return "", false, fmt.Errorf("decode HPA PR response: %w", err)
	}
	return pr.HTMLURL, true, nil
}
