{{- if .Values.githubToken }}
apiVersion: v1
kind: Secret
metadata:
  name: kri-operator-github
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: kri-operator
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  token: {{ .Values.githubToken | quote }}
{{- end }}
