package cmd

import (
	"bufio"
	"context"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/davidacain/platform-lab/tools/k8s-resource-inspector/pkg/config"
	"github.com/davidacain/platform-lab/tools/k8s-resource-inspector/pkg/github"
	"github.com/davidacain/platform-lab/tools/k8s-resource-inspector/pkg/gitops"
	"github.com/davidacain/platform-lab/tools/k8s-resource-inspector/pkg/output"
	"github.com/davidacain/platform-lab/tools/k8s-resource-inspector/pkg/plan"
	"github.com/spf13/cobra"
)

var applyAll bool
var dryRun bool

var applyCmd = &cobra.Command{
	Use:   "apply",
	Short: "Apply resource recommendations by opening PRs",
	Long: `apply opens one PR per app containing a values-resources.yaml with the
recommended resource changes.

Without --all, apply reads kri-plan.yaml (generated by kri plan). Edit the
file to set apply: false for any app you want to skip, then run kri apply.

With --all, apply runs the inspect pipeline, shows all findings, and prompts
for confirmation before opening PRs.`,
	RunE: runApply,
}

func init() {
	applyCmd.Flags().BoolVar(&applyAll, "all", false, "Run inspect pipeline and apply all recommendations")
	applyCmd.Flags().BoolVar(&dryRun, "dry-run", false, "Show what would be applied without opening PRs")
	applyCmd.Flags().StringVar(&window, "window", "7d", "Observation window (only used with --all)")
	applyCmd.Flags().Float64Var(&confidenceThreshold, "confidence", 0.8, "Confidence threshold (only used with --all)")
	rootCmd.AddCommand(applyCmd)
}

func runApply(cmd *cobra.Command, args []string) error {
	token := os.Getenv("GITHUB_TOKEN")
	if token == "" && !dryRun {
		return fmt.Errorf("GITHUB_TOKEN environment variable is not set")
	}

	var plans []plan.AppPlan

	if applyAll {
		p, err := buildPlansFromInspect()
		if err != nil {
			return err
		}
		plans = p
	} else {
		p, err := plan.Read()
		if err != nil {
			return err
		}
		plans = p
	}

	applicable := make([]plan.AppPlan, 0, len(plans))
	for _, p := range plans {
		if p.Apply {
			applicable = append(applicable, p)
		}
	}

	if len(applicable) == 0 {
		fmt.Println("Nothing to apply.")
		return nil
	}

	printApplySummary(applicable)

	if dryRun {
		fmt.Println("\n[dry-run] No PRs opened.")
		return nil
	}

	if !confirm("\nApply? [y/N] ") {
		fmt.Println("Aborted.")
		return nil
	}

	return openPRs(token, applicable)
}

// buildPlansFromInspect runs the full inspect pipeline, prints the table, and
// returns a plan list for all apps with actionable recommendations.
func buildPlansFromInspect() ([]plan.AppPlan, error) {
	ctx := context.Background()

	cfg, err := config.Load(configPath)
	if err != nil {
		return nil, fmt.Errorf("load config: %w", err)
	}

	dynClient, err := buildDynamicClient(kubeconfig, kubeCtx)
	if err != nil {
		return nil, fmt.Errorf("build kubernetes client: %w", err)
	}

	apps, err := listApps(ctx, dynClient)
	if err != nil {
		return nil, err
	}
	if len(apps) == 0 {
		return nil, nil
	}

	rows, err := buildRows(ctx, cfg, dynClient, apps, window, confidenceThreshold)
	if err != nil {
		return nil, err
	}

	sort.Slice(rows, func(i, j int) bool {
		a, b := rows[i], rows[j]
		if a.AppName != b.AppName {
			return a.AppName < b.AppName
		}
		if a.Namespace != b.Namespace {
			return a.Namespace < b.Namespace
		}
		if a.PodName != b.PodName {
			return a.PodName < b.PodName
		}
		return a.Container < b.Container
	})

	// Print the full table so the user sees what's driving the recommendations.
	if err := output.PrintTable(rows); err != nil {
		return nil, err
	}

	return plan.Build(rows), nil
}

func printApplySummary(plans []plan.AppPlan) {
	fmt.Printf("\n%d app(s) to update:\n\n", len(plans))
	for _, p := range plans {
		fmt.Printf("  %s\n", p.App)
		fmt.Printf("    repo:   %s\n", p.Repo)
		fmt.Printf("    file:   %s\n", p.ValuesFile)
		for _, c := range p.Containers {
			fmt.Printf("    %-20s  cpu %s  mem %s\n", c.Name, c.CPURequest, c.MemRequest)
		}
		fmt.Println()
	}
}

func openPRs(token string, plans []plan.AppPlan) error {
	for _, p := range plans {
		fmt.Printf("  %s  ", p.App)

		branch, err := gitops.PushValuesFile(p.Repo, token, p.App, p.ValuesFile[:strings.LastIndex(p.ValuesFile, "/")], p.Containers)
		if err != nil {
			fmt.Printf("FAILED: %v\n", err)
			continue
		}

		prURL, created, err := github.EnsurePR(token, p.Repo, branch, p.App, p.Containers)
		if err != nil {
			fmt.Printf("pushed branch %s, PR FAILED: %v\n", branch, err)
			continue
		}

		if created {
			fmt.Printf("PR opened: %s\n", prURL)
		} else {
			fmt.Printf("PR already open: %s\n", prURL)
		}
	}
	return nil
}

func confirm(prompt string) bool {
	fmt.Print(prompt)
	scanner := bufio.NewScanner(os.Stdin)
	if scanner.Scan() {
		return strings.ToLower(strings.TrimSpace(scanner.Text())) == "y"
	}
	return false
}
